language: node_js
os: linux
sudo: true
addons:
  apt:
    packages:
      - rsync
      - sshpass
node_js:
  - "node"
branches:
  only:
    - develop
install:
  - cd konfluence-web
  - npm i
script:
  - npm run build
after_success:
  - test $TRAVIS_BRANCH = "develop" && rsync -chavzP --rsh="sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no -l $SSH_USERNAME" dist/* $SSH_USERNAME@konfluence.xyz:/var/www/html/staging